language: php

php:
 - 7.1
 - 7.2
 - 7.3
 - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
 - travis_retry composer self-update
 - travis_retry composer update --no-interaction --prefer-source

script:
 - vendor/bin/phpunit --coverage-clover=coverage.xml
 - tools/ensure-docopt-readme-and-app-are-identical

after_success:
 - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: R3XOmZ+j5oCsqfYmJQcRQ+LY9x70Ht3MX3V8jd5Ze4ZqRAeod6ZdlAvk5ae8IcvhIUC/gfUZCEGDa+EWXhMRxNf4RPszK9D8Gcz/TxPT3lkZVg+zdz/Fa2vNtthCQGc+HqZU2dnWtK4RV6TH0yq0ra5ychG5fOXEKMfk28WdznPMqgQwdPthjKX6tihVtT6M5QgR40h2daN5sm7OGUPP4iorrwsAhceGzz2OZeMib30oWpblIFPBJ1Ibf7Q73+T8w8tdhA4zMYERQ4DLZUr5+V90GQNu6NZ4y2IJmDW1jKYKJS6VsfLuLXi8GoEik8SjIrgH0tzaFBQUCZej77HqphUdtasRAhRzG564gLjmWMAeuRQyiA0m8cltnCIGj+V5EEiY1D1weyTMrHa5+kEubi8RkzUHAKyxd2XTRTSPMIiJW/jzhyVEv5MpD9Ma44fu49zdbex8en3MgNvAMoH66YK79gULuU1+RDl7ulgAdlHehEZM2AQeYk37seKcAcZPWtFO47jVgR7K+dMohUxwLEGFLCkkvWSFh2nVKUiNMyeVe5Dcs6316W2dNTgGHfjWneUE3lK2gyEwAfrC3e9dxv+FytlxI+Tf8PIo5XSGYf0PkbipFT7BPe60fehFIIcxCYNteDXW93uG6g9fN+etstmWimKnKOEyRNYTCLCOsVE=
